org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.debug=false

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.53-beta
neo_version_range=[26.2.0.53-beta,26.3.0)
loader_version_range=[4,)

mod_id=sophisticatedstorage
mod_name=Sophisticated Storage
mod_license=All Rights Reserved
mod_version=1.5.112
mod_group_id=net.p3pp3rf1y
mod_authors=P3pp3rF1y, Ridanisaurus
mod_description=Fancy and functional storage containers.
mod_credits=Created by P3pp3rF1y and art by Ridanisaurus.
mod_logo_file=logo.png
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage
mod_issue_tracker_url=https://github.com/P3pp3rF1y/SophisticatedStorage/issues
sonar_project_key=sophisticatedstorage:SophisticatedStorage
github_package_url=https://maven.pkg.github.com/P3pp3rF1y/SophisticatedStorage

jei_mc_version=26.2-neoforge
jei_version=30.7.0.41
jei_version_range=[27.0.0,)
emi_version=1.1.22+1.21.1
rei_version=26.2.820
jade_cf_file_id=7313008
quark_cf_file_id=7640331
zeta_cf_file_id=7640154
chipped_cf_file_id=5506938
resourcefullib_cf_file_id=7806326
athena_cf_file_id=5431579
sawmill_cf_file_id=6119477
moonlightlib_cf_file_id=6224057
toms_storage_cf_file_id=7417413
sc_version=[26.2-1.4.102,26.3)
sb_version=[26.2-3.25.85,26.3)

# publish
curseforge_id=619320
release_type=release
release_versions=26.2
modrinth_project_id=hMlaZH8f
